def cmd_dict(send_func, recv_func):
    ''' The purpose of this function is to simplify and clean up the cmds
    dict listed below
    '''
    return {'send_func': send_func, 'recv_func': recv_func}

''' Actual JSON commands sent to message manager
Dict key is the internal generic message used in the DTU, also the key to get the actual JSON command
Values are another dictionary with the following items:
    send_func:  Name of function to call from CotaTransmitter to actually send the command
    recv_func:  Name of function to call in DTU to process received data

update_status is a generic function that prints the result of the last command to the status window
'''
cmds = {
    # DTU specific commands
    'CONNECT'               : cmd_dict('connect',              'on_connect'),
    'GET_ALL_CONFIG'        : cmd_dict('get_all_config',       'redraw_config'),
    'SAVE_ALL_CONFIG'       : cmd_dict('save_all_config',      'update_status'),
    'SEND_SYS_CMD'          : cmd_dict('sys_cmd',              'update_status'),
    'RX_LPM_STANDBY'        : cmd_dict('set_rx_lpm_standby',   'update_status'),
    'RX_DISP_UPDATE_TIME'   : cmd_dict('set_rx_screen_update', 'update_status'),
    'GET_SYSTEM_INFO'       : cmd_dict('get_sysinfo',          'redraw_sysinfo'),
    'QUIT'                  : cmd_dict('disconnect',           'clean_quit'),
    'SEARCH_FOR_TX'         : cmd_dict('search_for_tx',        'populate_tx_list'),
    'CONNECT_LOG'           : cmd_dict('connect_logman',       'update_ssh_status'),
    'LIST_LOGFILES'         : cmd_dict('list_logs',            'populate_loglist'),
    'DOWNLOAD_LOG'          : cmd_dict('download_log',         'update_ssh_status'),
    'DELETE_LOG'            : cmd_dict('delete_log',           'update_ssh_status'),
    'START_LOG'             : cmd_dict('start_logging',        'update_ssh_status'),
    'STOP_LOG'              : cmd_dict('stop_logging',         'update_ssh_status'),
    # Message manager specific commands
    # These keys will match keys in the Venus and Orion cmd dicts
    'app_command_data'      : cmd_dict('app_command_data',     'redraw_app_cmd_data'),
    'app_command'           : cmd_dict('app_cmd',              'update_status'),
    'calibrate'			    : cmd_dict('calibrate',            'update_status'),
    'charge_virtual'        : cmd_dict('charge_virtual',       'update_status'),
    'rx_config'             : cmd_dict('rx_config',            'update_status'),
    'rx_detail'             : cmd_dict('get_rx_detail',        'redraw_rx_detail'),
    'rx_leave'              : cmd_dict('rx_leave',             'redraw_rx_list'),
    'rx_list'               : cmd_dict('get_rx_list',          'redraw_rx_list'),
    'rx_lpm'                : cmd_dict('set_rx_lpm',           'update_status'),
    'rx_sleep'              : cmd_dict('rx_sleep',             'update_status'),
    'get_cfg_param'         : cmd_dict('get_cfg_param',        'redraw_config'),
    'get_tx_firmware'    	: cmd_dict('get_tx_firmware',      'redraw_sysinfo'),
    'get_tx_id'             : cmd_dict('get_tx_id',            'redraw_sysinfo'),
    'get_rx_data'	    	: cmd_dict('get_rx_data',          'redraw_rx_detail'),
    'get_comm_channel'      : cmd_dict('get_comm_channel',     'redraw_sysinfo'),
    'get_valid_ambs'        : cmd_dict('get_valid_ambs',       'redraw_sysinfo'),
    'get_power_level'		: cmd_dict('get_power_level',      'redraw_sysinfo'),
    'get_proxy_info'        : cmd_dict('get_proxy_info',       'update_status'),
    'get_system_state'		: cmd_dict('get_system_state',     'redraw_sysinfo'),
    'get_system_temp'		: cmd_dict('get_system_temp',      'redraw_sysinfo'),
    'get_mcu_log'   		: cmd_dict('get_mcu_log',          'display_mcu_log'),
    'reset_host'	    	: cmd_dict('reset_host',           'update_status'),
    'identify_tx'	    	: cmd_dict('identify_tx',          'update_status'),
    'identify_rx'	     	: cmd_dict('identify_rx',          'update_status'),
    'lpm_assign'            : cmd_dict('lpm_assign',           'update_status'),
    'lpm_free'              : cmd_dict('lpm_remove',           'update_status'),
    'lpm_list'              : cmd_dict('get_lpm_list',         'redraw_lpm_list'),
    'lpm_slots'             : cmd_dict('set_lpm_slots',        'redraw_lpm_list'),
    'lpm'                   : cmd_dict('set_tile_lpm',         'update_status'),
    'pause'                 : cmd_dict('pause',                'redraw_sysinfo'),
    'proxy_command_data'    : cmd_dict('proxy_command_data',   'update_status'),
    'proxy_command'         : cmd_dict('proxy_command',        'update_status'),
    'reboot'                : cmd_dict('reboot',               'update_status'),
    'register_rx'           : cmd_dict('register_rx',          'update_status'),
    'remove_rx'             : cmd_dict('unregister_rx',        'update_status'),
    'reset_array'           : cmd_dict('reset_array',          'update_status'),
    'reset_fpga'            : cmd_dict('reset_fpga',           'update_status'),
    'reset_nvm'             : cmd_dict('reset_nvm',            'update_status'),
    'reset_proxy'           : cmd_dict('reset_proxy',          'update_status'),
    'restart'               : cmd_dict('restart',              'update_status'),
    'rssi_report'           : cmd_dict('rssi_report',          'update_status'),
    'run'                   : cmd_dict('run',                  'redraw_sysinfo'),
    'send_disc'             : cmd_dict('send_discovery',       'update_status'),
    'set_cfg_param'         : cmd_dict('set_cfg_param',        'update_status'),
    'set_comm_channel'      : cmd_dict('set_comm_channel',     'redraw_sysinfo'),
    'set_fans_full'         : cmd_dict('set_fans_full',        'update_status'),
    'set_valid_ambs'        : cmd_dict('set_valid_ambs',       'redraw_sysinfo'),
    'set_power_level'       : cmd_dict('set_power_lvl',        'redraw_sysinfo'),
    'set_tx_freq'           : cmd_dict('set_tx_freq',          'redraw_sysinfo'),
    'shutdown'              : cmd_dict('shutdown',             'update_status'),
    'start_charging'        : cmd_dict('start_charging',       'update_status'),
    'status'                : cmd_dict('status',               'redraw_sysinfo'),
    'stop_charging'         : cmd_dict('stop_charging',        'update_status'),
}

# Orion config parameters
orion_cfg_params = {
    1 : "CFG_CONFIG_FILE_VERSION",
    0 : "CFG_BOARD_ID",
    2 : "CFG_CALIBRATION_UVP",
    3 : "CFG_CALIBRATION_AMB",
    4 : "CFG_CALIBRATION_AMU",
    5 : "CFG_REFERENCE_UVP",
    6 : "CFG_REFERENCE_AMB",
    7 : "CFG_REFERENCE_AMU",
    8 : "CFG_AUTO_CALIBRATION_PERIOD",
    9 : "CFG_CAL_TEMP_SMPL_PERIOD",
    10 : "CFG_CAL_TEMP_THRESHOLD",
    11 : "CFG_CHG_PRIORITY_THRESHOLD",
    12 : "CFG_COMM_CHANNEL",
    13 : "CFG_MAX_QUERIES",
    14 : "CFG_QUERY_PERIOD",
    15 : "CFG_CLIENT_QUERY_TIMEOUT",
    16 : "CFG_CLIENT_RESPONSE_TIMEOUT",
    17 : "CFG_CRITICAL_TEMPERATURE",
    18 : "CFG_DEBUG_MODE",
    19 : "CFG_DISCOVERY_PERIOD",
    20 : "CFG_DISCOVERY_TIMEOUT",
    21 : "CFG_DISCOVERY_WAIT",
    22 : "CFG_JOIN_PERIOD",
    23 : "CFG_JOIN_WAIT",
    24 : "CFG_TPC_PERIOD",
    25 : "CFG_TPC_WAIT",
    26 : "CFG_UVP_ENCODE_SIZE",
    27 : "CFG_VALID_AMB_MASK",
    28 : "CFG_LPM_SLOT_COUNT",
    29 : "CFG_MAX_QUERY_FAIL_COUNT",
    30 : "CFG_NETWORK_PAN_ID",
    31 : "CFG_STARTING_CLIENT_ID",
    32 : "CFG_PROXY_ID",
    33 : "CFG_OBSTRUCTION_ANGLE_THRESHOLD",
    34 : "CFG_PHASE_ADJUSTMENT_PERIOD",
    35 : "CFG_POWER_LEVEL",
    36 : "CFG_POWER_MODE",
    37 : "CFG_SHORT_CALIBRATION_DURATION",
    38 : "CFG_SHORT_CALIBRATION_PERIOD",
    39 : "CFG_SYSTEM_TYPE",
    40 : "CFG_TPS_NUM_BEACON_BEATS",
    41 : "CFG_TPS_NUM_CLIENTS",
    42 : "CFG_TPS_NUM_POWER_SLOTS",
    43 : "CFG_TPS_NUM_POWER_SLOTS_PER_CLIENT",
    44 : "CFG_TPS_PA_DELAY",
    45 : "CFG_TPS_RX_DELAY",
    46 : "CFG_TPS_RX_DURATION",
    47 : "CFG_TPS_START_DELAY",
    48 : "CFG_PRE_TPS_CLIENT_PAUSE",
    49 : "CFG_POST_TPS_CLIENT_PAUSE",
    50 : "CFG_TPS_TX_DURATION",
    51 : "CFG_TPS_TIMEOUT",
    52 : "CFG_TX_FREQUENCY_MHZ",
    53 : "CFG_SYSTEM_CLOCK",
    54 : "CFG_VALID_FANS",
    55 : "CFG_APP_COMMAND_TIMEOUT",
    56 : "CFG_APP_COMMAND_MAX_SEND",
    57 : "CFG_DISC_CLIENT_TIMEOUT",
    58 : "CFG_DISC_CLIENT_MAX_SEND",
    59 : "CFG_LIGHT_RING_UPDATE_PERIOD",
    60 : "CFG_SYSCLK_AMPLITUDE",
    61 : "CFG_SYSCLK_COMMON_MODE",
    62 : "CFG_SYSCLK_FORMAT",
    63 : "CFG_SYSCLK_AMB_INVERSION",
    64 : "CFG_SYSCLK_IDLE_DISABLE",
    65 : "CFG_SYS_LOG_LEVEL",
    66 : "CFG_APP_CMD_MAX_TRIES",
    67 : "CFG_PROXY_TEST_PERIOD",
    68 : "CFG_PROXY_TEST_WAIT_TIMEOUT",
    69 : "CFG_DOOR_OPEN_MSG_PERIOD",
    70 : "CFG_RCVR_LONG_CONFIG_RESP_TIMEOUT",
    71 : "CFG_XIRGO_SLEEP_TIME",
    72 : "CFG_RCVR_CHARGING_THRESHOLD",
    73 : "CFG_RCVR_COMM_PWR",
    74 : "CFG_ETHERNET_CLOCK_STATE",
    75 : "CFG_FATAL_LOW_HIST_MIN",
    76 : "CFG_FATAL_LOW_HIST_MAX",
    77 : "CFG_MAX_NUM_OF_FATAL_LOW_RCVRS",
    78 : "CFG_WAIT_FOR_SLEEP_TIMEOUT",
    79 : "CFG_RECEIVER_REMOVAL_PERIOD",
    80 : "CFG_RCVR_SHORT_CONFIG_RESP_TIMEOUT",
    81 : "CFG_PROXY_ANNOUNCEMENT_DELAY",
    82 : "CFG_PROXY_RSSI_FILTER_MIN_VAL",
}
