#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  May 08, 2021 10:58:37 AM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1275x620
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1275 640
    wm minsize $top 1275 640
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "CotaDTU"
    vTcl:DefineAlias "$top" "CotaDTU_Top" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(complement_color)]
    ttk::notebook $top.tNo46 \
        -width 1084 -height 606 -takefocus {} 
    vTcl:DefineAlias "$top.tNo46" "CotaNotebook" vTcl:WidgetProc "CotaDTU_Top" 1
    frame $top.tNo46.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t0" "CotaNotebookDemo" vTcl:WidgetProc "CotaDTU_Top" 1
    $top.tNo46 add $top.tNo46.t0 \
        -padding 0 -sticky nsew -state normal -text Demo -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo46.t0
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr49 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_0.scr49" "clientListTree" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_0.scr49 <<TreeviewSelect>> {
        lambda e: select_rx(e)
    }
    bind $site_4_0.scr49 <Control-Key-c> {
        lambda e: copy_id(e)
    }

    .top42.tNo46.t0.scr49.01 configure -columns "Col1 Col2" \
        -height 4
        .top42.tNo46.t0.scr49.01 configure -columns {Col1 Col2}
        .top42.tNo46.t0.scr49.01 heading #0 -text {Receiver ID}
        .top42.tNo46.t0.scr49.01 heading #0 -anchor center
        .top42.tNo46.t0.scr49.01 column #0 -width 150
        .top42.tNo46.t0.scr49.01 column #0 -minwidth 20
        .top42.tNo46.t0.scr49.01 column #0 -stretch 0
        .top42.tNo46.t0.scr49.01 column #0 -anchor center
        .top42.tNo46.t0.scr49.01 heading Col1 -text {Link Quality}
        .top42.tNo46.t0.scr49.01 heading Col1 -anchor center
        .top42.tNo46.t0.scr49.01 column Col1 -width 100
        .top42.tNo46.t0.scr49.01 column Col1 -minwidth 20
        .top42.tNo46.t0.scr49.01 column Col1 -stretch 0
        .top42.tNo46.t0.scr49.01 column Col1 -anchor center
        .top42.tNo46.t0.scr49.01 heading Col2 -text {Status}
        .top42.tNo46.t0.scr49.01 heading Col2 -anchor center
        .top42.tNo46.t0.scr49.01 column Col2 -width 211
        .top42.tNo46.t0.scr49.01 column Col2 -minwidth 20
        .top42.tNo46.t0.scr49.01 column Col2 -stretch 1
        .top42.tNo46.t0.scr49.01 column Col2 -anchor center
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr50 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_0.scr50" "clientDetailTree" vTcl:WidgetProc "CotaDTU_Top" 1

    .top42.tNo46.t0.scr50.01 configure -columns Col1 \
        -height 4
        .top42.tNo46.t0.scr50.01 configure -columns {Col1}
        .top42.tNo46.t0.scr50.01 heading #0 -text {Parameter}
        .top42.tNo46.t0.scr50.01 heading #0 -anchor center
        .top42.tNo46.t0.scr50.01 column #0 -width 230
        .top42.tNo46.t0.scr50.01 column #0 -minwidth 20
        .top42.tNo46.t0.scr50.01 column #0 -stretch 0
        .top42.tNo46.t0.scr50.01 column #0 -anchor w
        .top42.tNo46.t0.scr50.01 heading Col1 -text {Value}
        .top42.tNo46.t0.scr50.01 heading Col1 -anchor center
        .top42.tNo46.t0.scr50.01 column Col1 -width 231
        .top42.tNo46.t0.scr50.01 column Col1 -minwidth 20
        .top42.tNo46.t0.scr50.01 column Col1 -stretch 1
        .top42.tNo46.t0.scr50.01 column Col1 -anchor w
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr51 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_0.scr51" "sysinfoTree" vTcl:WidgetProc "CotaDTU_Top" 1

    .top42.tNo46.t0.scr51.01 configure -columns Col1 \
        -height 4
        .top42.tNo46.t0.scr51.01 configure -columns {Col1}
        .top42.tNo46.t0.scr51.01 heading #0 -text {Parameter}
        .top42.tNo46.t0.scr51.01 heading #0 -anchor center
        .top42.tNo46.t0.scr51.01 column #0 -width 167
        .top42.tNo46.t0.scr51.01 column #0 -minwidth 20
        .top42.tNo46.t0.scr51.01 column #0 -stretch 1
        .top42.tNo46.t0.scr51.01 column #0 -anchor w
        .top42.tNo46.t0.scr51.01 heading Col1 -text {Value}
        .top42.tNo46.t0.scr51.01 heading Col1 -anchor center
        .top42.tNo46.t0.scr51.01 column Col1 -width 167
        .top42.tNo46.t0.scr51.01 column Col1 -minwidth 20
        .top42.tNo46.t0.scr51.01 column Col1 -stretch 1
        .top42.tNo46.t0.scr51.01 column Col1 -anchor w
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $site_4_0.tFr59 \
        -borderwidth 2 -relief groove -width 350 -height 165 
    vTcl:DefineAlias "$site_4_0.tFr59" "clientCmdFrame" vTcl:WidgetProc "CotaDTU_Top" 1
    set site_5_0 $site_4_0.tFr59
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu60 \
        -takefocus {} -text Register 
    vTcl:DefineAlias "$site_5_0.tBu60" "regBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu60 <ButtonRelease-1> {
        lambda e: demo_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu61 \
        -takefocus {} -text {Start Charge} 
    vTcl:DefineAlias "$site_5_0.tBu61" "startChgBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu61 <ButtonRelease-1> {
        lambda e: demo_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu62 \
        -takefocus {} -text Unregister 
    vTcl:DefineAlias "$site_5_0.tBu62" "unRegBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu62 <ButtonRelease-1> {
        lambda e: demo_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu63 \
        -takefocus {} -text {Stop Charge} 
    vTcl:DefineAlias "$site_5_0.tBu63" "stopChgBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu63 <ButtonRelease-1> {
        lambda e: demo_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu65 \
        -takefocus {} -text Sleep 
    vTcl:DefineAlias "$site_5_0.tBu65" "sleepCltBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu65 <ButtonRelease-1> {
        lambda e: demo_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu44 \
        -takefocus {} -text Identify 
    vTcl:DefineAlias "$site_5_0.tBu44" "identClientBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu44 <ButtonRelease-1> {
        lambda e: demo_rx_btn(e)
    }
    place $site_5_0.tBu60 \
        -in $site_5_0 -x 20 -y 20 -width 136 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu61 \
        -in $site_5_0 -x 20 -y 50 -width 136 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu62 \
        -in $site_5_0 -x 180 -y 20 -width 136 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu63 \
        -in $site_5_0 -x 180 -y 50 -width 136 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu65 \
        -in $site_5_0 -x 180 -y 80 -width 136 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu44 \
        -in $site_5_0 -x 20 -y 80 -width 136 -height 25 -anchor nw \
        -bordermode ignore 
    ttk::label $site_4_0.tLa66 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Receiver List} 
    vTcl:DefineAlias "$site_4_0.tLa66" "clientListLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_0.tLa67 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Receiver Details} 
    vTcl:DefineAlias "$site_4_0.tLa67" "clientDetailLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_0.tLa68 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {System Info} 
    vTcl:DefineAlias "$site_4_0.tLa68" "sysinfoLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_0.tLa69 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Receiver Commands} 
    vTcl:DefineAlias "$site_4_0.tLa69" "clientCmdLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    button $site_4_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief sunken 
    vTcl:DefineAlias "$site_4_0.but46" "ossiaLogoBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $site_4_0.tFr44 \
        -borderwidth 2 -relief groove -width 175 -height 265 
    vTcl:DefineAlias "$site_4_0.tFr44" "txCmdFrame" vTcl:WidgetProc "CotaDTU_Top" 1
    set site_5_0 $site_4_0.tFr44
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu50 \
        -takefocus {} -text {Send Discovery} 
    vTcl:DefineAlias "$site_5_0.tBu50" "sendDiscBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu50 <ButtonRelease-1> {
        lambda e: sys_btn_cmd(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu51 \
        -takefocus {} -text {Identify Transmitter} 
    vTcl:DefineAlias "$site_5_0.tBu51" "identifyBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu51 <ButtonRelease-1> {
        lambda e: sys_btn_cmd(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu52 \
        -takefocus {} -text Calibrate 
    vTcl:DefineAlias "$site_5_0.tBu52" "calibrateBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu52 <ButtonRelease-1> {
        lambda e: sys_btn_cmd(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu46 \
        -takefocus {} -text Shutdown 
    vTcl:DefineAlias "$site_5_0.tBu46" "shutdownBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu46 <ButtonRelease-1> {
        lambda e: sys_btn_cmd(e)
    }
    place $site_5_0.tBu50 \
        -in $site_5_0 -x 20 -y 70 -width 136 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tBu51 \
        -in $site_5_0 -x 20 -y 10 -width 136 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tBu52 \
        -in $site_5_0 -x 20 -y 40 -width 136 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tBu46 \
        -in $site_5_0 -x 0 -relx 0.114 -y 0 -rely 0.377 -width 136 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    ttk::label $site_4_0.tLa54 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Transmitter Commands} 
    vTcl:DefineAlias "$site_4_0.tLa54" "txCmdLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    place $site_4_0.scr49 \
        -in $site_4_0 -x 10 -y 40 -width 480 -relwidth 0 -height 167 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr50 \
        -in $site_4_0 -x 10 -y 270 -width 480 -relwidth 0 -height 267 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr51 \
        -in $site_4_0 -x 510 -y 270 -width 0 -relwidth 0.278 -height 0 \
        -relheight 0.46 -anchor nw -bordermode ignore 
    place $site_4_0.tFr59 \
        -in $site_4_0 -x 510 -y 40 -width 350 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa66 \
        -in $site_4_0 -x 10 -y 19 -width 100 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa67 \
        -in $site_4_0 -x 10 -y 247 -width 85 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa68 \
        -in $site_4_0 -x 510 -y 250 -width 85 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa69 \
        -in $site_4_0 -x 510 -y 20 -width 170 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 900 -y 40 -width 367 -relwidth 0 -height 164 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tFr44 \
        -in $site_4_0 -x 0 -relx 0.7 -y 0 -rely 0.466 -width 0 \
        -relwidth 0.138 -height 0 -relheight 0.457 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa54 \
        -in $site_4_0 -x 890 -y 250 -width 145 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo46.t3 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t3" "CotaNotebookLPM" vTcl:WidgetProc "CotaDTU_Top" 1
    $top.tNo46 add $top.tNo46.t3 \
        -padding 0 -sticky nsew -state normal -text ESL -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo46.t3
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_1.scr91 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_1.scr91" "lpmSlotListTree" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_1.scr91 <<TreeviewSelect>> {
        lambda e: select_lpm_slot(e)
    }

    .top42.tNo46.t3.scr91.01 configure -columns "Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8" \
        -height 4 \
        -cursor arrow
        .top42.tNo46.t3.scr91.01 configure -columns {Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8}
        .top42.tNo46.t3.scr91.01 heading #0 -text {Receiver ID}
        .top42.tNo46.t3.scr91.01 heading #0 -anchor center
        .top42.tNo46.t3.scr91.01 column #0 -width 142
        .top42.tNo46.t3.scr91.01 column #0 -minwidth 20
        .top42.tNo46.t3.scr91.01 column #0 -stretch 1
        .top42.tNo46.t3.scr91.01 column #0 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col1 -text {Slot}
        .top42.tNo46.t3.scr91.01 heading Col1 -anchor center
        .top42.tNo46.t3.scr91.01 column Col1 -width 61
        .top42.tNo46.t3.scr91.01 column Col1 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col1 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col1 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col2 -text {Antenna}
        .top42.tNo46.t3.scr91.01 heading Col2 -anchor center
        .top42.tNo46.t3.scr91.01 column Col2 -width 81
        .top42.tNo46.t3.scr91.01 column Col2 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col2 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col2 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col3 -text {Charge (mV)}
        .top42.tNo46.t3.scr91.01 heading Col3 -anchor center
        .top42.tNo46.t3.scr91.01 column Col3 -width 82
        .top42.tNo46.t3.scr91.01 column Col3 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col3 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col3 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col4 -text {LPM}
        .top42.tNo46.t3.scr91.01 heading Col4 -anchor center
        .top42.tNo46.t3.scr91.01 column Col4 -width 52
        .top42.tNo46.t3.scr91.01 column Col4 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col4 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col4 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col5 -text {RSSI}
        .top42.tNo46.t3.scr91.01 heading Col5 -anchor center
        .top42.tNo46.t3.scr91.01 column Col5 -width 52
        .top42.tNo46.t3.scr91.01 column Col5 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col5 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col5 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col6 -text {Update (m)}
        .top42.tNo46.t3.scr91.01 heading Col6 -anchor center
        .top42.tNo46.t3.scr91.01 column Col6 -width 82
        .top42.tNo46.t3.scr91.01 column Col6 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col6 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col6 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col7 -text {Time}
        .top42.tNo46.t3.scr91.01 heading Col7 -anchor center
        .top42.tNo46.t3.scr91.01 column Col7 -width 92
        .top42.tNo46.t3.scr91.01 column Col7 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col7 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col7 -anchor center
        .top42.tNo46.t3.scr91.01 heading Col8 -text {Status}
        .top42.tNo46.t3.scr91.01 heading Col8 -anchor center
        .top42.tNo46.t3.scr91.01 column Col8 -width 167
        .top42.tNo46.t3.scr91.01 column Col8 -minwidth 20
        .top42.tNo46.t3.scr91.01 column Col8 -stretch 1
        .top42.tNo46.t3.scr91.01 column Col8 -anchor center
    ttk::label $site_4_1.tLa55 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Receiver List} 
    vTcl:DefineAlias "$site_4_1.tLa55" "lpmClientListLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_1.tLa56 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {ESL List} 
    vTcl:DefineAlias "$site_4_1.tLa56" "lpmSlotListLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_1.scr44 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_1.scr44" "lpmRxListTree" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_1.scr44 <<TreeviewSelect>> {
        lambda e: select_rx(e)
    }

    .top42.tNo46.t3.scr44.01 configure -columns Col1 \
        -height 4
        .top42.tNo46.t3.scr44.01 configure -columns {Col1}
        .top42.tNo46.t3.scr44.01 heading #0 -text {Receiver ID}
        .top42.tNo46.t3.scr44.01 heading #0 -anchor center
        .top42.tNo46.t3.scr44.01 column #0 -width 150
        .top42.tNo46.t3.scr44.01 column #0 -minwidth 20
        .top42.tNo46.t3.scr44.01 column #0 -stretch 0
        .top42.tNo46.t3.scr44.01 column #0 -anchor center
        .top42.tNo46.t3.scr44.01 heading Col1 -text {Status}
        .top42.tNo46.t3.scr44.01 heading Col1 -anchor center
        .top42.tNo46.t3.scr44.01 column Col1 -width 161
        .top42.tNo46.t3.scr44.01 column Col1 -minwidth 20
        .top42.tNo46.t3.scr44.01 column Col1 -stretch 1
        .top42.tNo46.t3.scr44.01 column Col1 -anchor center
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $site_4_1.tFr47 \
        -borderwidth 2 -relief groove -width 1238 -height 75 
    vTcl:DefineAlias "$site_4_1.tFr47" "lpmSysCmdFrame" vTcl:WidgetProc "CotaDTU_Top" 1
    set site_5_0 $site_4_1.tFr47
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu48 \
        -takefocus {} -text {Slot Count} 
    vTcl:DefineAlias "$site_5_0.tBu48" "lpmSetSlotsBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu48 <ButtonRelease-1> {
        lambda e: lpm_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu51 \
        -takefocus {} -text Calibrate 
    vTcl:DefineAlias "$site_5_0.tBu51" "lpmCalBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu51 <ButtonRelease-1> {
        lambda e: sys_btn_cmd(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu44 \
        -takefocus {} -text {Start Charging} 
    vTcl:DefineAlias "$site_5_0.tBu44" "lpmStartChargeBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu44 <ButtonRelease-1> {
        lambda e: lpm_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu45 \
        -takefocus {} -text {Stop Charging} 
    vTcl:DefineAlias "$site_5_0.tBu45" "lpmStopChargeBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu45 <ButtonRelease-1> {
        lambda e: lpm_rx_btn(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu46 \
        -takefocus {} -text {Load List} 
    vTcl:DefineAlias "$site_5_0.tBu46" "lpmLoadWhitelistBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_5_0.tBu46 <ButtonRelease-1> {
        lambda e: lpm_load_whitelist(e)
    }
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu47 \
        -command start_auto_assignment -takefocus {} -text {Start Auto} 
    vTcl:DefineAlias "$site_5_0.tBu47" "lpmStartAssignBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu49 \
        -command stop_auto_assignment -takefocus {} -text {Stop Auto} 
    vTcl:DefineAlias "$site_5_0.tBu49" "lpmStopAssignBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu50 \
        -command display_whitelist -takefocus {} -text {View List} 
    vTcl:DefineAlias "$site_5_0.tBu50" "lpmViewWhitelistBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    place $site_5_0.tBu48 \
        -in $site_5_0 -x 10 -y 40 -width 85 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu51 \
        -in $site_5_0 -x 10 -y 10 -width 85 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu44 \
        -in $site_5_0 -x 410 -y 10 -width 95 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu45 \
        -in $site_5_0 -x 410 -y 40 -width 95 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu46 \
        -in $site_5_0 -x 100 -y 10 -width 65 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu47 \
        -in $site_5_0 -x 170 -y 10 -width 65 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu49 \
        -in $site_5_0 -x 170 -y 40 -width 65 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu50 \
        -in $site_5_0 -x 100 -y 40 -width 65 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_1.tBu55 \
        -takefocus {} -text {Assign >} 
    vTcl:DefineAlias "$site_4_1.tBu55" "lpmAddBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_1.tBu55 <ButtonRelease-1> {
        lambda e: lpm_rx_btn(e)
    }
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_1.scr64 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_1.scr64" "lpmRxDetailTree" vTcl:WidgetProc "CotaDTU_Top" 1

    .top42.tNo46.t3.scr64.01 configure -columns Col1 \
        -height 4
        .top42.tNo46.t3.scr64.01 configure -columns {Col1}
        .top42.tNo46.t3.scr64.01 heading #0 -text {Parameter}
        .top42.tNo46.t3.scr64.01 heading #0 -anchor center
        .top42.tNo46.t3.scr64.01 column #0 -width 150
        .top42.tNo46.t3.scr64.01 column #0 -minwidth 20
        .top42.tNo46.t3.scr64.01 column #0 -stretch 0
        .top42.tNo46.t3.scr64.01 column #0 -anchor w
        .top42.tNo46.t3.scr64.01 heading Col1 -text {Value}
        .top42.tNo46.t3.scr64.01 heading Col1 -anchor center
        .top42.tNo46.t3.scr64.01 column Col1 -width 162
        .top42.tNo46.t3.scr64.01 column Col1 -minwidth 20
        .top42.tNo46.t3.scr64.01 column Col1 -stretch 1
        .top42.tNo46.t3.scr64.01 column Col1 -anchor w
    ttk::label $site_4_1.tLa65 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {System Commands} 
    vTcl:DefineAlias "$site_4_1.tLa65" "lpmSysCmdsLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_1.tLa66 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Receiver Details} 
    vTcl:DefineAlias "$site_4_1.tLa66" "lpmDetailLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    place $site_4_1.scr91 \
        -in $site_4_1 -x 420 -y 50 -width 830 -relwidth 0 -height 387 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tLa55 \
        -in $site_4_1 -x 10 -y 30 -width 0 -relwidth 0.079 -height 0 \
        -relheight 0.033 -anchor nw -bordermode ignore 
    place $site_4_1.tLa56 \
        -in $site_4_1 -x 420 -y 30 -width 0 -relwidth 0.06 -height 0 \
        -relheight 0.033 -anchor nw -bordermode ignore 
    place $site_4_1.scr44 \
        -in $site_4_1 -x 10 -y 50 -width 330 -relwidth 0 -height 157 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tFr47 \
        -in $site_4_1 -x 10 -y 450 -width 1238 -relwidth 0 -height 75 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tBu55 \
        -in $site_4_1 -x 0 -relx 0.275 -y 0 -rely 0.086 -width 65 -height 25 \
        -anchor nw -bordermode ignore 
    place $site_4_1.scr64 \
        -in $site_4_1 -x 0 -relx 0.008 -y 0 -rely 0.431 -width 0 \
        -relwidth 0.26 -height 0 -relheight 0.288 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa65 \
        -in $site_4_1 -x 10 -y 430 -width 117 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa66 \
        -in $site_4_1 -x 10 -y 230 -width 100 -height 19 -anchor nw \
        -bordermode ignore 
    frame $top.tNo46.t4 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t4" "CotaNotebookDebug" vTcl:WidgetProc "CotaDTU_Top" 1
    $top.tNo46 add $top.tNo46.t4 \
        -padding 0 -sticky nsew -state normal -text Debug -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo46.t4
    ttk::label $site_4_2.tLa65 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Receiver List} 
    vTcl:DefineAlias "$site_4_2.tLa65" "debugClientListLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_2.scr69 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_2.scr69" "debugClientListTree" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_2.scr69 <<TreeviewSelect>> {
        lambda e: select_rx(e)
    }
    bind $site_4_2.scr69 <Control-Key-c> {
        lambda e: copy_id(e)
    }

    .top42.tNo46.t4.scr69.01 configure -columns "Col1 Col2" \
        -height 4
        .top42.tNo46.t4.scr69.01 configure -columns {Col1 Col2}
        .top42.tNo46.t4.scr69.01 heading #0 -text {Receiver ID}
        .top42.tNo46.t4.scr69.01 heading #0 -anchor center
        .top42.tNo46.t4.scr69.01 column #0 -width 150
        .top42.tNo46.t4.scr69.01 column #0 -minwidth 20
        .top42.tNo46.t4.scr69.01 column #0 -stretch 0
        .top42.tNo46.t4.scr69.01 column #0 -anchor center
        .top42.tNo46.t4.scr69.01 heading Col1 -text {Link Quality}
        .top42.tNo46.t4.scr69.01 heading Col1 -anchor center
        .top42.tNo46.t4.scr69.01 column Col1 -width 100
        .top42.tNo46.t4.scr69.01 column Col1 -minwidth 20
        .top42.tNo46.t4.scr69.01 column Col1 -stretch 0
        .top42.tNo46.t4.scr69.01 column Col1 -anchor center
        .top42.tNo46.t4.scr69.01 heading Col2 -text {Status}
        .top42.tNo46.t4.scr69.01 heading Col2 -anchor center
        .top42.tNo46.t4.scr69.01 column Col2 -width 150
        .top42.tNo46.t4.scr69.01 column Col2 -minwidth 20
        .top42.tNo46.t4.scr69.01 column Col2 -stretch 1
        .top42.tNo46.t4.scr69.01 column Col2 -anchor center
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu44 \
        -command load_cota_config -takefocus {} -text Load 
    vTcl:DefineAlias "$site_4_2.tBu44" "loadConfigBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu45 \
        -command save_cota_config -takefocus {} -text Save 
    vTcl:DefineAlias "$site_4_2.tBu45" "saveConfigBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_2.scr46 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_2.scr46" "cotaConfigTree" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_2.scr46 <Double-Button-1> {
        lambda e: CotaDTU_support.edit_config_val(e)
    }

    .top42.tNo46.t4.scr46.01 configure -columns Col1 \
        -height 4
        .top42.tNo46.t4.scr46.01 configure -columns {Col1}
        .top42.tNo46.t4.scr46.01 heading #0 -text {Parameter}
        .top42.tNo46.t4.scr46.01 heading #0 -anchor center
        .top42.tNo46.t4.scr46.01 column #0 -width 200
        .top42.tNo46.t4.scr46.01 column #0 -minwidth 20
        .top42.tNo46.t4.scr46.01 column #0 -stretch 1
        .top42.tNo46.t4.scr46.01 column #0 -anchor w
        .top42.tNo46.t4.scr46.01 heading Col1 -text {Value}
        .top42.tNo46.t4.scr46.01 heading Col1 -anchor center
        .top42.tNo46.t4.scr46.01 column Col1 -width 200
        .top42.tNo46.t4.scr46.01 column Col1 -minwidth 20
        .top42.tNo46.t4.scr46.01 column Col1 -stretch 1
        .top42.tNo46.t4.scr46.01 column Col1 -anchor w
    ttk::label $site_4_2.tLa48 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Transmitter Configuration} 
    vTcl:DefineAlias "$site_4_2.tLa48" "configParamsLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa50 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Transmitter Commands} 
    vTcl:DefineAlias "$site_4_2.tLa50" "advTxCmdFrameLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa49 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Receiver Commands} 
    vTcl:DefineAlias "$site_4_2.tLa49" "clientCmdLbl_2" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu46 \
        -command send_app_cmd -takefocus {} -text Send 
    vTcl:DefineAlias "$site_4_2.tBu46" "sendCltCmdBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu47 \
        -command get_app_cmd_data -takefocus {} -text Read 
    vTcl:DefineAlias "$site_4_2.tBu47" "getCltDataBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $site_4_2.tEn48 \
        -font TkTextFont -width 316 -foreground {} -background {} \
        -takefocus {} -cursor arrow 
    vTcl:DefineAlias "$site_4_2.tEn48" "clientCmdRespEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text Response 
    vTcl:DefineAlias "$site_4_2.tLa51" "clientCmdDataRespLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $site_4_2.tEn52 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor arrow 
    vTcl:DefineAlias "$site_4_2.tEn52" "clientCmdSendEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_2.scr53 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_2.scr53" "advancedRxList" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_2.scr53 <ButtonRelease-1> {
        lambda e: clear_user_args(e)
    }

    $site_4_2.scr53.01 configure -activestyle dotbox \
        -background white \
        -cursor arrow \
        -disabledforeground #a3a3a3 \
        -exportselection 0 \
        -font "-family {Courier New} -size 10" \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #0076d7 \
        -selectforeground #ffffff \
        -selectmode single \
        -width 10
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu48 \
        -command send_tx_cmd -takefocus {} -text Send 
    vTcl:DefineAlias "$site_4_2.tBu48" "sendAdvancedTxBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $site_4_2.tEn49 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor arrow 
    vTcl:DefineAlias "$site_4_2.tEn49" "sendAdvTxEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $site_4_2.tEn50 \
        -font TkTextFont -width 316 -foreground {} -background {} \
        -takefocus {} -cursor arrow 
    vTcl:DefineAlias "$site_4_2.tEn50" "advTxRespEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text Response 
    vTcl:DefineAlias "$site_4_2.tLa52" "advTxRespLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_2.scr54 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_2.scr54" "advancedTxList" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_2.scr54 <ButtonRelease-1> {
        lambda e: clear_user_args(e)
    }

    $site_4_2.scr54.01 configure -activestyle dotbox \
        -background white \
        -cursor arrow \
        -disabledforeground #a3a3a3 \
        -exportselection 0 \
        -font "-family {Courier New} -size 10" \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #0076d7 \
        -selectforeground #ffffff \
        -selectmode single \
        -width 10
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu49 \
        -command download_log_file -takefocus {} -text Download 
    vTcl:DefineAlias "$site_4_2.tBu49" "downloadLogBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu50 \
        -command delete_log_file -takefocus {} -text Delete 
    vTcl:DefineAlias "$site_4_2.tBu50" "deleteLogBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Receiver Logs} 
    vTcl:DefineAlias "$site_4_2.tLa53" "logListLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu54 \
        -command list_log_files -takefocus {} -text {List Files} 
    vTcl:DefineAlias "$site_4_2.tBu54" "listLogsBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu55 \
        -command start_logging -takefocus {} -text {Start Logging} 
    vTcl:DefineAlias "$site_4_2.tBu55" "startLogBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu57 \
        -command stop_logging -takefocus {} -text {Stop Logging} 
    vTcl:DefineAlias "$site_4_2.tBu57" "stopLogBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $site_4_2.tEn58 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor arrow 
    vTcl:DefineAlias "$site_4_2.tEn58" "logHrsEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $site_4_2.tEn59 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor arrow 
    vTcl:DefineAlias "$site_4_2.tEn59" "logDelayEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa60 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text Hours 
    vTcl:DefineAlias "$site_4_2.tLa60" "logHrsLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa61 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Delay (s)} 
    vTcl:DefineAlias "$site_4_2.tLa61" "logDelayLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa63 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Receiver Logging} 
    vTcl:DefineAlias "$site_4_2.tLa63" "logCtrlLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_2.scr45 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_2.scr45" "logfileTree" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $site_4_2.scr45 <Double-Button-1> {
        lambda e: CotaDTU_support.edit_config_val(e)
    }

    .top42.tNo46.t4.scr45.01 configure -columns Col1 \
        -height 4
        .top42.tNo46.t4.scr45.01 configure -columns {Col1}
        .top42.tNo46.t4.scr45.01 heading #0 -text {Filename}
        .top42.tNo46.t4.scr45.01 heading #0 -anchor center
        .top42.tNo46.t4.scr45.01 column #0 -width 221
        .top42.tNo46.t4.scr45.01 column #0 -minwidth 20
        .top42.tNo46.t4.scr45.01 column #0 -stretch 1
        .top42.tNo46.t4.scr45.01 column #0 -anchor w
        .top42.tNo46.t4.scr45.01 heading Col1 -text {Size (kb)}
        .top42.tNo46.t4.scr45.01 heading Col1 -anchor center
        .top42.tNo46.t4.scr45.01 column Col1 -width 81
        .top42.tNo46.t4.scr45.01 column Col1 -minwidth 20
        .top42.tNo46.t4.scr45.01 column Col1 -stretch 1
        .top42.tNo46.t4.scr45.01 column Col1 -anchor w
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu51 \
        -command connect_ssh -takefocus {} -text {Connect SSH} 
    vTcl:DefineAlias "$site_4_2.tBu51" "connectSshBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $site_4_2.tEn53 \
        -font TkTextFont -width 316 -foreground {} -background {} \
        -takefocus {} -cursor arrow 
    vTcl:DefineAlias "$site_4_2.tEn53" "sshRespEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa54 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text Response 
    vTcl:DefineAlias "$site_4_2.tLa54" "sshResponseLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa45 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Transmitter Logs} 
    vTcl:DefineAlias "$site_4_2.tLa45" "txLogListLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu52 \
        -command get_mcu_log -takefocus {} -text {View MCU Log} 
    vTcl:DefineAlias "$site_4_2.tBu52" "mcuLogBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $site_4_2.tLa46 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Data Plotting} 
    vTcl:DefineAlias "$site_4_2.tLa46" "logPlotLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu53 \
        -command log_plot_dialog -takefocus {} -text {Plot Log Data} 
    vTcl:DefineAlias "$site_4_2.tBu53" "plotDataBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    place $site_4_2.tLa65 \
        -in $site_4_2 -x 10 -y 19 -width 75 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.scr69 \
        -in $site_4_2 -x 10 -y 40 -width 419 -relwidth 0 -height 197 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu44 \
        -in $site_4_2 -x 10 -y 490 -anchor nw -bordermode ignore 
    place $site_4_2.tBu45 \
        -in $site_4_2 -x 90 -y 490 -anchor nw -bordermode ignore 
    place $site_4_2.scr46 \
        -in $site_4_2 -x 10 -y 270 -width 419 -relwidth 0 -height 207 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tLa48 \
        -in $site_4_2 -x 10 -y 247 -width 155 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tLa50 \
        -in $site_4_2 -x 0 -relx 0.359 -y 0 -rely 0.431 -width 0 \
        -relwidth 0.122 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa49 \
        -in $site_4_2 -x 460 -y 19 -width 170 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu46 \
        -in $site_4_2 -x 460 -y 160 -width 56 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu47 \
        -in $site_4_2 -x 580 -y 160 -width 56 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn48 \
        -in $site_4_2 -x 460 -y 210 -width 316 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tLa51 \
        -in $site_4_2 -x 460 -y 190 -width 55 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn52 \
        -in $site_4_2 -x 527 -y 162 -width 46 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.scr53 \
        -in $site_4_2 -x 460 -y 40 -width 322 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu48 \
        -in $site_4_2 -x 0 -relx 0.362 -y 0 -rely 0.69 -width 56 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn49 \
        -in $site_4_2 -x 527 -y 403 -width 46 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn50 \
        -in $site_4_2 -x 460 -y 450 -width 316 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tLa52 \
        -in $site_4_2 -x 460 -y 430 -width 75 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_2.scr54 \
        -in $site_4_2 -x 458 -y 270 -width 325 -relwidth 0 -height 125 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu49 \
        -in $site_4_2 -x 0 -relx 0.708 -y 0 -rely 0.569 -width 76 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu50 \
        -in $site_4_2 -x 0 -relx 0.775 -y 0 -rely 0.569 -width 76 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tLa53 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.31 -width 0 \
        -relwidth 0.061 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tBu54 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.569 -width 76 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu55 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.121 -width 136 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu57 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.172 -width 136 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn58 \
        -in $site_4_2 -x 0 -relx 0.763 -y 0 -rely 0.124 -width 46 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn59 \
        -in $site_4_2 -x 0 -relx 0.81 -y 0 -rely 0.124 -width 0 \
        -relwidth 0.035 -height 0 -relheight 0.036 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa60 \
        -in $site_4_2 -x 0 -relx 0.763 -y 0 -rely 0.086 -width 0 \
        -relwidth 0.042 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa61 \
        -in $site_4_2 -x 0 -relx 0.81 -y 0 -rely 0.086 -width 0 \
        -relwidth 0.052 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa63 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.034 -width 0 \
        -relwidth 0.083 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.scr45 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.348 -width 0 \
        -relwidth 0.253 -height 0 -relheight 0.217 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tBu51 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.069 -width 136 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tEn53 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.259 -width 0 \
        -relwidth 0.249 -height 0 -relheight 0.036 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa54 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.224 -width 0 \
        -relwidth 0.042 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tLa45 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.74 -width 0 \
        -relwidth 0.083 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tBu52 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.772 -width 136 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tLa46 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.638 -width 0 \
        -relwidth 0.083 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tBu53 \
        -in $site_4_2 -x 0 -relx 0.641 -y 0 -rely 0.672 -width 136 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    menu $top.m47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $top.m47 add cascade \
        -menu "$top.m47.men48" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label File 
    set site_3_0 $top.m47
    menu $site_3_0.men48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men48 add command \
        -command {#log_plot_dialog} -label {Open Log} 
    $site_3_0.men48 add command \
        -command {#search_for_tx} -label Search 
    $site_3_0.men48 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command {#send_disconnect} \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Quit 
    $top.m47 add cascade \
        -menu "$top.m47.men88" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Edit 
    set site_3_0 $top.m47
    menu $site_3_0.men88 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men88 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command {#enable_debug_tab} \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Debug 
    $site_3_0.men88 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command {#set_upd_interval} \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) \
        -label {Update Interval} 
    $top.m47 add cascade \
        -menu "$top.m47.men90" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(actual_gui_bg) \
        -font TkMenuFont -foreground $vTcl(pr,menufgcolor) -label Help 
    set site_3_0 $top.m47
    menu $site_3_0.men90 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men90 add command \
        -command {#display_help_file} -label {Open Help} 
    ttk::label $top.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text Hostname: 
    vTcl:DefineAlias "$top.tLa53" "hostEntLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu54 \
        -command connect -takefocus {} -text Connect 
    vTcl:DefineAlias "$top.tBu54" "connectBtn" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::label $top.tLa55 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text Status: 
    vTcl:DefineAlias "$top.tLa55" "statusLbl" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::entry $top.tEn56 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor arrow 
    vTcl:DefineAlias "$top.tEn56" "lastStatusEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    ttk::combobox $top.tCo47 \
        -font TkTextFont -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo47" "hostEntry" vTcl:WidgetProc "CotaDTU_Top" 1
    bind $top.tCo47 <Key-Return> {
        lambda e: connect(e)
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo46 \
        -in $top -x 0 -y 40 -width 1275 -relwidth 0 -height 606 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 10 -y 10 -width 62 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu54 \
        -in $top -x 250 -y 8 -width 76 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa55 \
        -in $top -x 970 -y 10 -width 39 -relwidth 0 -height 19 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tEn56 \
        -in $top -x 1020 -y 10 -width 226 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo47 \
        -in $top -x 80 -y 10 -width 164 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

