#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 16, 2021 02:53:37 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import LogPlottingGUI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Plot_Data_GUI (root)
    LogPlottingGUI_support.init(root, top)
    root.mainloop()

w = None
def create_Plot_Data_GUI(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Plot_Data_GUI(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Plot_Data_GUI (w)
    LogPlottingGUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Plot_Data_GUI():
    global w
    w.destroy()
    w = None

class Plot_Data_GUI:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("527x409")
        top.minsize(120, 1)
        top.maxsize(6490, 1422)
        top.resizable(1,  1)
        top.title("Plot Data")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.plotButton = tk.Button(top)
        self.plotButton.place(relx=0.038, rely=0.733, height=34, width=207)
        self.plotButton.configure(activebackground="#ececec")
        self.plotButton.configure(activeforeground="#000000")
        self.plotButton.configure(background="#d9d9d9")
        self.plotButton.configure(command=LogPlottingGUI_support.plot_data)
        self.plotButton.configure(disabledforeground="#a3a3a3")
        self.plotButton.configure(foreground="#000000")
        self.plotButton.configure(highlightbackground="#d9d9d9")
        self.plotButton.configure(highlightcolor="black")
        self.plotButton.configure(pady="0")
        self.plotButton.configure(text='''Plot''')

        self.rxListBox = ScrolledListBox(top)
        self.rxListBox.place(relx=0.038, rely=0.073, relheight=0.526
                , relwidth=0.4)
        self.rxListBox.configure(background="white")
        self.rxListBox.configure(cursor="arrow")
        self.rxListBox.configure(disabledforeground="#a3a3a3")
        self.rxListBox.configure(exportselection="0")
        self.rxListBox.configure(font="TkFixedFont")
        self.rxListBox.configure(foreground="black")
        self.rxListBox.configure(highlightbackground="#d9d9d9")
        self.rxListBox.configure(highlightcolor="#d9d9d9")
        self.rxListBox.configure(selectbackground="#c4c4c4")
        self.rxListBox.configure(selectforeground="black")
        self.rxListBox.configure(selectmode='extended')

        self.columnListBox = ScrolledListBox(top)
        self.columnListBox.place(relx=0.474, rely=0.073, relheight=0.526
                , relwidth=0.457)
        self.columnListBox.configure(background="white")
        self.columnListBox.configure(cursor="arrow")
        self.columnListBox.configure(disabledforeground="#a3a3a3")
        self.columnListBox.configure(exportselection="0")
        self.columnListBox.configure(font="TkFixedFont")
        self.columnListBox.configure(foreground="black")
        self.columnListBox.configure(highlightbackground="#d9d9d9")
        self.columnListBox.configure(highlightcolor="#d9d9d9")
        self.columnListBox.configure(selectbackground="#c4c4c4")
        self.columnListBox.configure(selectforeground="black")
        self.columnListBox.configure(selectmode='extended')

        self.rxListLbl = ttk.Label(top)
        self.rxListLbl.place(relx=0.038, rely=0.024, height=19, width=95)
        self.rxListLbl.configure(background="#d9d9d9")
        self.rxListLbl.configure(foreground="#000000")
        self.rxListLbl.configure(font="TkDefaultFont")
        self.rxListLbl.configure(relief="flat")
        self.rxListLbl.configure(text='''Receiver IDs''')

        self.dataColumnLbl = ttk.Label(top)
        self.dataColumnLbl.place(relx=0.474, rely=0.024, height=19, width=75)
        self.dataColumnLbl.configure(background="#d9d9d9")
        self.dataColumnLbl.configure(foreground="#000000")
        self.dataColumnLbl.configure(font="TkDefaultFont")
        self.dataColumnLbl.configure(relief="flat")
        self.dataColumnLbl.configure(text='''Data Selection''')

        self.fileBrowseBtn = tk.Button(top)
        self.fileBrowseBtn.place(relx=0.038, rely=0.636, height=34, width=207)
        self.fileBrowseBtn.configure(activebackground="#ececec")
        self.fileBrowseBtn.configure(activeforeground="#000000")
        self.fileBrowseBtn.configure(background="#d9d9d9")
        self.fileBrowseBtn.configure(command=LogPlottingGUI_support.open_file)
        self.fileBrowseBtn.configure(disabledforeground="#a3a3a3")
        self.fileBrowseBtn.configure(foreground="#000000")
        self.fileBrowseBtn.configure(highlightbackground="#d9d9d9")
        self.fileBrowseBtn.configure(highlightcolor="black")
        self.fileBrowseBtn.configure(pady="0")
        self.fileBrowseBtn.configure(text='''Select File''')

        self.closeBtn = tk.Button(top)
        self.closeBtn.place(relx=0.038, rely=0.831, height=34, width=207)
        self.closeBtn.configure(activebackground="#ececec")
        self.closeBtn.configure(activeforeground="#000000")
        self.closeBtn.configure(background="#d9d9d9")
        self.closeBtn.configure(command=LogPlottingGUI_support.destroy_window)
        self.closeBtn.configure(disabledforeground="#a3a3a3")
        self.closeBtn.configure(foreground="#000000")
        self.closeBtn.configure(highlightbackground="#d9d9d9")
        self.closeBtn.configure(highlightcolor="black")
        self.closeBtn.configure(pady="0")
        self.closeBtn.configure(text='''Close''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.instructionsLbl = ttk.Label(top)
        self.instructionsLbl.place(relx=0.493, rely=0.66, height=99, width=225)
        self.instructionsLbl.configure(background="#d9d9d9")
        self.instructionsLbl.configure(foreground="#000000")
        self.instructionsLbl.configure(font="TkDefaultFont")
        self.instructionsLbl.configure(relief="flat")
        self.instructionsLbl.configure(anchor='w')
        self.instructionsLbl.configure(justify='left')
        self.instructionsLbl.configure(wraplength="220")
        self.instructionsLbl.configure(text='''To plot data, first select a log file. Then select one or more receivers from the list of Receiver IDs. Then select one or more data columns. Finally, click the Plot button.''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





